### ISSUE TITLE
Strange behavior with Key Names under Settings

### ISSUE THREAD

**Issue by mchalunderscore** [MSPFA/MSPFA#138]
I've noticed some strange behaviors on the user settings page when setting keybinds.

In my use case, my mouse allows me to bind up to 3 different buttons to some keys that I rarely use, which I can then hook up to ReWASD for extra usability (I tend to suffer from typing-related RSI)

There are some keys that when inputted for the Controls either show strange names or the name of a completely different key, I've compiled the list of ones I've noticed so far below:

| Key Pressed | Key Name on MSPFA | Extra Notes |
|---|---|---|
| -/_ | Audio Volume Mute |  |
| =/+ | Key #61 |  |
| End | Key #35 | The HOME key shows up correctly |
| Volume Mute | Key #181 | An unorthodox choice, but -/_ showing as Mute made me curious as to how this would show up |
| Right Alt | Control |  |
| Volume + | Launch Application 2 | Again, inspired by -/_ seemingly registering as a volume key |

**Comment by GrantGryczan** [comment]
I am unable to reproduce this issue. It might be an issue with your setup.

Also, this repository is for MSPFA v3, which is currently unreleased. If you want to report a bug with the current website, I would do so in the site-devlog channel on the [MSPFA Discord server](https://mspfa.com/discord).
